config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only:    :edit
  resources :password_resets,     except: [:destroy, :index, :show]
  resources :microposts,          only:   [:create, :destroy]
  resources :relationships,       only:   [:create, :destroy]
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,         only: [:edit, :update]
  before_action :valid_user,       only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      #valid email address
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "نحوه تغییر رمزعبور به آدرس #{@user.email} ارسال شد!"
      redirect_to root_url
    else
      #invalid email address
      flash.now[:danger] = "پست الکترونیک پیدا نشد!"
      render 'new'
    end
  end

  def edit
  end

  def update
    #NOTE because we "allow_blank: true" in password validation
    if(params[:user][:password].blank?) #catch blank password & password_confirmation
       @user.errors.add(:password, "لطفاً رمزعبور مورد نظرتان را وارد کنید!")
       render 'edit'
    elsif @user.update_attributes(user_params) #Successful
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "رمزعبور با موفقیت تغییر کرد!"
      redirect_to @user
    else #Invalid password
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  ##Before Filters##
  def get_user
    @user = User.find_by(email: params[:email])
  end
  #Confirms a valid user and correct reset_token
  def valid_user
    unless (@user && @user.activated? &&
            @user.authenticated?(:reset, params[:id]))
      redirect_to root_url
    end
  end

  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = "پیوند بازیابی رمزعبور باطل شده است! لطفاً دوباره درخواست کنید."
      redirect_to new_password_reset_url
    end
  end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'بازیابی رمز عبور') %>
<h1>بازیابی رمزعبور</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%-# id is the token actually -%>
    <%= form_for(@user, url: password_reset_url(params[:id])) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, "رمز عبور" %>
      <%= f.password_field :password, class: "form-control", placeholder: "(حداقل ۶ نویسه)" %>

      <%= f.label :password_confirmation, "تکرار" %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "(تکرار رمز عبور)" %>
      <%= f.submit "به روز رسانی", class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "بازیابی رمزعبور") %>
<h1>رمز عبورم را فراموش کردم!</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>

        <%= f.label :email, "پست الکترونیک" %>
        <%= f.text_field :email, class: "form-control", placeholder: "folan@bisar.ir" %>

      <%= f.submit "ثبت", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>